 LES ATTIBUTS A EVITER  DANS UN DOCTIONNAIRE DE DONNEES :
 1- LES CONSTANTES
 2- LES DONNEES ELABOREES : COMME LES DONNEES CALCULES (tva,pht, ptc=pht*(1+tva/100)  A EVITER )
                            : ET LES DONNEES DEDUITES : AGE , DATEDENAISSANCE

LES FORMES NORMALES : (FN)
FN1 : CHAQUE ATTRIBUTS DOIR ETRE ATOMIQUE (MONO VALEUR)
FN2 : FN1 OK, SI ON UN ID SIMPLE, cette FN est deja respectee
FN3: FN2 SONT OK,  CHAQUE ATTRIBUT DOIT DEPENDRE "DIRECTEMENT " DE L'ID

A DEPEND DE B 
SI A CHANGE B CHANGE 




association porteuse




REGLES DE PASSAGE DE MCD VERS MLD(MODELE LOGIQUE DE DONNEES) 
R1 : ENTITE => TABLE 
ATTRIBUT => COLONNE
IDENTIFIANT => CLE PRIMAIRE (PRIMARY KEY : PK)
R2 : CAS D'UNE RELATION N-1 : PK COTE N=>FK (CLE ETRANGER ) COTE 1
R3 : CAS D'UNE RELATION N:N : LES PK DEVIENNENT DES FK DANS LA RELATION AU MILIEU
 

 MPD : MODELE PHYSIQUE DE DONNEES = MLD  DANS UN SGBDR PRECIS (MYSQL , SQL SERVER)
